/*
 * DIO_private.h
 *
 * Created: 3/6/2024 7:15:17 PM
 *  Author: Ziad Ashraf
 */ 


#ifndef DIO_PRIVATE_H_
#define DIO_PRIVATE_H_

//concatenate all pins for each port
#define DIO_PORTA_DIRECTION CONC_BIT(DIO_PIN7_DIRECTION,DIO_PIN6_DIRECTION,DIO_PIN5_DIRECTION,DIO_PIN4_DIRECTION,DIO_PIN3_DIRECTION,DIO_PIN2_DIRECTION,DIO_PIN1_DIRECTION,DIO_PIN0_DIRECTION);
#define DIO_PORTB_DIRECTION CONC_BIT(DIO_PIN15_DIRECTION,DIO_PIN14_DIRECTION,DIO_PIN13_DIRECTION,DIO_PIN12_DIRECTION,DIO_PIN11_DIRECTION,DIO_PIN10_DIRECTION,DIO_PIN9_DIRECTION,DIO_PIN8_DIRECTION);
#define DIO_PORTC_DIRECTION CONC_BIT(DIO_PIN23_DIRECTION,DIO_PIN22_DIRECTION,DIO_PIN21_DIRECTION,DIO_PIN20_DIRECTION,DIO_PIN19_DIRECTION,DIO_PIN18_DIRECTION,DIO_PIN17_DIRECTION,DIO_PIN16_DIRECTION);
#define DIO_PORTD_DIRECTION CONC_BIT(DIO_PIN31_DIRECTION,DIO_PIN30_DIRECTION,DIO_PIN29_DIRECTION,DIO_PIN28_DIRECTION,DIO_PIN27_DIRECTION,DIO_PIN26_DIRECTION,DIO_PIN25_DIRECTION,DIO_PIN24_DIRECTION);


#endif /* DIO_PRIVATE_H_ */