/*
 * DIO_config.h
 *
 * Created: 3/6/2024 7:15:31 PM
 *  Author: Ziad Ashraf
 */ 


#ifndef DIO_CONFIG_H_
#define DIO_CONFIG_H_

//to configure the pin direction select (DIO_PIN_INPUT or DIO_PIN_OUTPUT)

//pins of port A from 0 -> 7
#define DIO_PIN0_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN1_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN2_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN3_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN4_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN5_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN6_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN7_DIRECTION		DIO_PIN_OUTPUT

//pins of port B from 8 -> 15
#define DIO_PIN8_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN9_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN10_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN11_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN12_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN13_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN14_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN15_DIRECTION		DIO_PIN_OUTPUT

//pins of port C from 16 -> 23
#define DIO_PIN16_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN17_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN18_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN19_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN20_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN21_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN22_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN23_DIRECTION		DIO_PIN_OUTPUT

//pins of port D from 24 -> 31
#define DIO_PIN24_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN25_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN26_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN27_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN28_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN29_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN30_DIRECTION		DIO_PIN_OUTPUT
#define DIO_PIN31_DIRECTION		DIO_PIN_OUTPUT



#endif /* DIO_CONFIG_H_ */