/*
 * LCD_private.h
 *
 * Created: 3/7/2024 7:08:25 PM
 *  Author: Ziad Ashraf
 */ 


#ifndef LCD_PRIVATE_H_
#define LCD_PRIVATE_H_

#define LCD_BEGINNING_FIRST_LINE		0x80
#define LCD_BEGINNING_SECOND_LINE		0xC0
#define LCD_BEGINNING_THIRD_LINE		0x94
#define LCD_BEGINNING_FOURTH_LINE		0xD4


#define DONOT_CARE 0

#define LCD_FUNCTION_SET			CONC_BIT(0,0,1,1,LCD_NO_OF_LINES,LCD_CHAR_FONT,DONOT_CARE,DONOT_CARE)
#define LCD_DISPLAY_ON_OFF_CONTROL	CONC_BIT(0,0,0,0,1,DISPLAY_STATUS,CURSOR_DISPLAY,CURSOR_BLINK)
#define LCD_DISPLAY_CLEAR			0x01
#define LCD_ENTRY_MODE_SET			CONC_BIT(0,0,0,0,0,1,DISPLAY_DIRECTION,DISPLAY_SHIFT)

//#define NUM_OF_SPECIAL_CHAR				8
//#define NUM_OF_SPECIA_CHAR_BYTES		8

#endif /* LCD_PRIVATE_H_ */